language: node_js
node_js:
  - 'node'
  - '10'
  - '8'

jobs:
  include:
    - stage: npm release
      if: tag IS present
      script: node build.js
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
